CREATE SCHEMA IF NOT EXISTS MA_STUDENT;

DROP TABLE IF EXISTS MA_STUDENT.OFFICES;

 CREATE TABLE MA_STUDENT.OFFICES
( OFFICE DECIMAL(38,0),
CITY VARCHAR(0),
REGION VARCHAR(0),
MGR DECIMAL(38,0),
TARGET DECIMAL(38,0),
SALES DECIMAL(38,0),


	)

